version: '3'
services:
  influxdb:
    image: influxdb:2.0.8-alpine
    container_name: influxdb2
    restart: always
    volumes:
      # Mount for influxdb data directory and configuration
      - ../influxdbData:/var/lib/influxdb2
      - ./config.yml:/etc/influxdb2/config.yml
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
    environment:
      # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=smms
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=SMMS
      - DOCKER_INFLUXDB_INIT_BUCKET=smmsbucket
#  telegraf:
#    image: telegraf
#    links:
#      - influxdb
#    volumes:
#      # Mount for telegraf config
#      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
#    env_file:
#      - ./influxv2.env
#    environment:
#      - DOCKER_INFLUXDB_INIT_ORG=myorg
#      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
#      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
#    depends_on:
#      - influxdb_cli
#volumes:
#  influxdbv2:
#    name: influxdbv2